name: "Camera Snapshot"
slug: "camera_snapshot"
description: "HTTP server providing stable snapshots for go2rtc from multiple cameras"
version: "1.0.0"
arch:
  - aarch64
  - amd64
  - armv7
  - armhf
  - i386
startup: services
boot: auto
host_network: true
options:
  interval: 10
  cameras:
    - name: "main"
      url: "http://homeassistant.local:XXXX/api/frame.jpeg?src=camera1"
    - name: "side"
      url: "http://homeassistant.local:XXXX/api/frame.jpeg?src=camera2"
schema:
  interval: int(5, 60)
  cameras:
    - name: str
      url: str
